### ISSUE TITLE
Test Question

### ISSUE THREAD

**Issue by zhaoker666** [mousecpn/Boosting-R-CNN-Reweighting-R-CNN-Samples-by-RPN-s-Error-for-Underwater-Object-Detection#17]
Hi,can i help me ? 
Traceback (most recent call last):
  File "/home/zk/anaconda3/envs/BRCNN/Boosting-R-CNN-master/tools/test.py", line 238, in <module>
    main()
  File "/home/zk/anaconda3/envs/BRCNN/Boosting-R-CNN-master/tools/test.py", line 203, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir,
  File "/home/zk/anaconda3/envs/BRCNN/Boosting-R-CNN-master/mmdet/apis/test.py", line 72, in single_gpu_test
    num_gts = gt_bboxes[i].shape[1]
UnboundLocalError: local variable 'gt_bboxes' referenced before assignment

**Comment by mousecpn** [comment]
(1) How did you compile the environment? Locally or use pip to install mmdet.
(2) Did you change the config script as:
<img width="862" alt="image" src="https://github.com/mousecpn/Boosting-R-CNN/assets/46233799/05d68662-32f0-474d-b7a0-2c1c5b1e7576">

**Comment by Sticker-Sjh** [comment]
测试问题在作者大大的帮助下，解决了这个问题，在mmdet/apis/test.py文件中把img = imshow_det_bboxes_water()整个注释掉，然后把下面的img = imshow_det_bboxes()取消注释就好了，再一次感谢作者

**Comment by mousecpn** [comment]
This bug is fixed.

> 测试问题在作者大大的帮助下，解决了这个问题，在mmdet/apis/test.py文件中把img = imshow_det_bboxes_water()整个注释掉，然后把下面的img = imshow_det_bboxes()取消注释就好了，再一次感谢作者
